module.exports ={
  'likes': '{likes, number} me gusta',
  'logout': 'Salir',
  'english': 'Inglés',
  'spanish': 'Español',
  'signup.subheading': 'Regístrate para ver fotos de tus amigos estudiando en Gamercast',
  'signup.facebook': 'Iniciar sesión con Facebook',
  'signup.text': 'Iniciar Sesión',
  'email': 'Correo electrónico',
  'username': 'Nombre de Usuario',
  'fullname': 'Nombre completo',
  'password': 'contraseña',
  'signup.call-to-action': 'Regístrate',
  'signup.have-account': '¿Tienes una cuenta?',
  'signin':'Entrar',
  'signin.not-have-account': '¿No tienes una cuenta?',
  'language':'Idioma',
  'upload-picture': 'Subir Foto',
  'upload': 'subir'
}
